version: '3.7'
services:
    api:
        build: .
        ports:
            - "5002:5000"
        volumes:
            - .:/code
        depends_on:
            - db_bot
    db_bot:
        image: postgres:12
        env_file:
          - .env
        volumes:
          - postgres_data:/var/lib/postgresql/data/

    adminer:
      image: adminer
      ports:
        - "81:8080"

volumes:
  postgres_data: