version: '3.7'
services:
    api:
        build: .
        ports:
            - "5002:5000"
        volumes:
            - .:/code
        depends_on:
            - db_bot
    db_bot:
        image: postgres:12
        environment:
            POSTGRES_USER: teste
            POSTGRES_PASSWORD: teste
            POSTGRES_DB: scrapy_db
        ports:
            - "5432:5432"
        volumes:
          - postgres_data:/var/lib/postgresql/data/

    adminer:
      image: adminer
      ports:
        - "81:8080"

volumes:
  postgres_data: